/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ManufacturingAdminRole;

import business.Business.Business;
import business.Enterprise.Enterprise;
import business.Enterprise.ManufacturingEnterprise;
import business.Organisation.Organisation;
import business.Product.FinalProduct;
import business.UserAccount.UserAccount;
import business.WorkQueue.WorkQueue;
import business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jayanti
 */
public class AdminAssignWorkJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminAssignWorkJPanel
     */
    JPanel workJPanel;
    UserAccount userAccount;
    Business business;
    WorkQueue wq;
    ManufacturingEnterprise enterprise;
//    ManufactureOrganisation organisation;
    
    public AdminAssignWorkJPanel(JPanel workJPanel, UserAccount userAccount) {
        initComponents();
        this.workJPanel = workJPanel;
        this.userAccount = userAccount;
        this.business = Business.getInstance();
        this.wq = this.business.getGlobalWorkQueue();
        this.enterprise = business.getManufacturingEnterprise();
        populateTable();
        addEventListener();
        jButton4.setVisible(false);
//        this.wq.getListOfRequests().j
    }
    
    public void populateTable(){
        DefaultTableModel requested = (DefaultTableModel) jTable1.getModel();
        jTable1.removeAll();
        for (WorkRequest wr: wq.getListOfRequests()){
            if (wr.getFromEnterprise().equals(this.business.getRetailerEnterprise())){
                Object[] row = new Object[5];
                row[0] = this.enterprise.findProduct(wr.getProductId());
                row[1] = wr.getQuantity();
                row[2] = this.enterprise.getInventory().get(wr.getProductId());
                row[3] = wr.getDateOfRequest();
                row[4] = wr.getStatus();
                
                requested.addRow(row);
            }
        }
    }
    
    public void addEventListener(){
        ListSelectionModel selectionModel = jTable1.getSelectionModel();

            // Add a ListSelectionListener to the selection model
            selectionModel.addListSelectionListener(new ListSelectionListener() {
                public void valueChanged(ListSelectionEvent e) {
                    if (!e.getValueIsAdjusting()) {
                        int selectedRow = jTable1.getSelectedRow();
                        if (selectedRow != -1) {
                            jButton4.setVisible(true);
                            int requiredQuantity = (int)jTable1.getValueAt(selectedRow, 1);
                            int availableQuantity = (int)jTable1.getValueAt(selectedRow, 2);
                            if (requiredQuantity <= availableQuantity){
                                JOptionPane.showMessageDialog(null, "Congratulations work request can be successfully completed");
                                jButton4.setText("Complete Work Request");
                            } else {
                                int amtSendForProcessing = requiredQuantity - availableQuantity;
                                JOptionPane.showMessageDialog(null, "Send for processing amount: " + amtSendForProcessing);
                                jButton4.setText("Send for processing the required quantity");
                                createNewWorkRequest((FinalProduct)jTable1.getValueAt(selectedRow, 0), amtSendForProcessing);
                            }
                        }
                    }
                }
            });
    }
    
    public void createNewWorkRequest(FinalProduct fp, int amt){
        WorkRequest wr = this.business.getGlobalWorkQueue().addWorkRequest();
        wr.setQuantity(amt);
        wr.setFromEnterprise(enterprise);
        wr.setForEnterprise(enterprise);
        wr.setStatus("From Supplier");
        wr.setProductId(fp.getId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Incoming Requests");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Requested Final Product", "Requested Quantity", "Avail Quantity", "Date of Request", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton4.setText("Hidden Button");

        jButton1.setText("View Inventory Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton1))
                .addContainerGap(385, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0){
            System.out.println("nothing is selected");
        } else {
            System.out.println(selectedRow);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
